---
apiVersion: v1
kind: Secret
metadata:
  name: mysqldb-credentials
type: Opaque
stringData:
  conjur-map: |-   
    username: data/vault/cityapp/cityappmysql/username
    password: data/vault/cityapp/cityappmysql/password
    address: data/vault/cityapp/cityappmysql/address
    
